name: flutter_demo
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  bloc: ^8.1.3
  cupertino_icons: ^1.0.2
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.4
  go_router: ^13.2.0
  very_good_analysis: ^5.1.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/background.png

  fonts:
    - family: Mada
      fonts:
        - asset: assets/fonts/mada/Mada-Black.ttf
          weight: 900
        - asset: assets/fonts/mada/Mada-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/mada/Mada-Bold.ttf
          weight: 700
        - asset: assets/fonts/mada/Mada-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/mada/Mada-Medium.ttf
          weight: 500
        - asset: assets/fonts/mada/Mada-Regular.ttf
          weight: 400
        - asset: assets/fonts/mada/Mada-Light.ttf
          weight: 300
        - asset: assets/fonts/mada/Mada-Light.ttf
          weight: 200
